[package]
name = "kura"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
criterion = "0.4.0"
image = "0.24.3"
rustface = "0.1.7"
